default:	COMPILATION_INST1	COMPILATION_INST2	COMPILATION_INST3	COMPILATION_INST4	COMPIATION_INST5	COMPILATION_INST6

COMPILATION_INST1:	ex1.cpp
	g++ -o ex1 -Wall ex1.cpp

COMPILATION_INST2:	ex2.cpp
	g++ -o ex2 -Wall ex2.cpp

COMPILATION_INST3:	testWindGauge.cpp
	g++ -o windgauge -Wall testWindGauge.cpp	WindGauge.cpp

COMPILATION_INST4:	ex4.cpp
	g++ -o ex4 -Wall ex4.cpp

COMPIATION_INST5:	ex5.cpp
	g++ -o ex5 -Wall ex5.cpp

COMPILATION_INST6:	ex6.cpp
	g++ -o ex6 -Wall ex6.cpp
